export const ACTIVATE_SERACHBAR = "ACTIVATE_SERACHBAR";
export const INA_CTIVE_SERACHBAR = "INA_CTIVE_SERACHBAR";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
